/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "zone-select": {
    name: "zone-select",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","label","command","popover","https://laviecn.vercel.app/r/use-filter-zone.json"],
    files: [{
      path: "registry/components/zone-select.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/zone-select.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "zone-filter": {
    name: "zone-filter",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","input","scroll-area","https://laviecn.vercel.app/r/use-filter-zone.json"],
    files: [{
      path: "registry/components/zone-filter.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/zone-filter.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-to-top": {
    name: "scroll-to-top",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/components/scroll-to-top.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/scroll-to-top.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "json-table": {
    name: "json-table",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","input","scroll-area","table","utils"],
    files: [{
      path: "registry/components/json-table.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/json-table.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "horizontal-scroll-menu": {
    name: "horizontal-scroll-menu",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","utils"],
    files: [{
      path: "registry/components/horizontal-scroll-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/horizontal-scroll-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "multiple-selector": {
    name: "multiple-selector",
    description: "",
    type: "registry:component",
    registryDependencies: ["command","utils","cmdk"],
    files: [{
      path: "registry/components/multiple-selector.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/multiple-selector.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "password-input": {
    name: "password-input",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","input","utils"],
    files: [{
      path: "registry/components/password-input.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/password-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "counting-number": {
    name: "counting-number",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/components/counting-number.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/counting-number.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sliding-number": {
    name: "sliding-number",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/components/sliding-number.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/sliding-number.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "smooth-cursor": {
    name: "smooth-cursor",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/components/smooth-cursor.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/smooth-cursor.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle": {
    name: "theme-toggle",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","utils"],
    files: [{
      path: "registry/components/theme-toggle.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/theme-toggle.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "zone-select-demo": {
    name: "zone-select-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/zone-select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/zone-select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "zone-filter-demo": {
    name: "zone-filter-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/zone-filter-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/zone-filter-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-to-top-demo": {
    name: "scroll-to-top-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/scroll-to-top-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-to-top-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sotienthanhchu-demo": {
    name: "sotienthanhchu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/sotienthanhchu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/sotienthanhchu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "json-table-demo": {
    name: "json-table-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/json-table-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/json-table-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "horizontal-scroll-menu-demo": {
    name: "horizontal-scroll-menu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/horizontal-scroll-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/horizontal-scroll-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "multiple-selector-demo": {
    name: "multiple-selector-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/multiple-selector-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/multiple-selector-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "password-input-demo": {
    name: "password-input-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/password-input-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/password-input-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "counting-number-demo": {
    name: "counting-number-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/counting-number-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/counting-number-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sliding-number-demo": {
    name: "sliding-number-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/sliding-number-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/sliding-number-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "smooth-cursor-demo": {
    name: "smooth-cursor-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/smooth-cursor-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/smooth-cursor-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle-demo": {
    name: "theme-toggle-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/theme-toggle-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-toggle-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "use-filter-zone": {
    name: "use-filter-zone",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-filter-zone.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/use-filter-zone.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sotienthanhchu": {
    name: "sotienthanhchu",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/utils/sotienthanhchu.ts",
      type: "registry:lib",
      target: "utils/sotienthanhchu.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/utils/sotienthanhchu.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "login-01": {
    name: "login-01",
    description: "login-01",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/blocks/login-01/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx"
    },{
      path: "registry/blocks/login-01/login-form.tsx",
      type: "registry:component",
      target: "sections/auth/login-form.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/login-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["login"],
    meta: undefined,
  },
  "header-01": {
    name: "header-01",
    description: "header-01",
    type: "registry:block",
    registryDependencies: ["button","navigation-menu","utils","https://laviecn.vercel.app/r/theme-toggle.json"],
    files: [{
      path: "registry/blocks/header/header-01/layout.tsx",
      type: "registry:page",
      target: "app/(home)/layout.tsx"
    },{
      path: "registry/blocks/header/header-01/header.tsx",
      type: "registry:component",
      target: "layouts/home/header/header-01/header.tsx"
    },{
      path: "registry/blocks/header/header-01/mobile-nav-trigger.tsx",
      type: "registry:component",
      target: "layouts/home/header/header-01/mobile-nav-trigger.tsx"
    },{
      path: "registry/blocks/header/nav-config.tsx",
      type: "registry:component",
      target: "layouts/home/header/nav-config.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/header/header-01/layout.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["header"],
    meta: undefined,
  },
  "header-02": {
    name: "header-02",
    description: "header-02",
    type: "registry:block",
    registryDependencies: ["button","navigation-menu","sheet","sidebar","utils","https://laviecn.vercel.app/r/theme-toggle.json"],
    files: [{
      path: "registry/blocks/header/header-02/layout.tsx",
      type: "registry:page",
      target: "app/(home)/layout.tsx"
    },{
      path: "registry/blocks/header/header-02/header.tsx",
      type: "registry:component",
      target: "layouts/home/header/header-02/header.tsx"
    },{
      path: "registry/blocks/header/header-02/mobile-nav-trigger.tsx",
      type: "registry:component",
      target: "layouts/home/header/header-02/mobile-nav-trigger.tsx"
    },{
      path: "registry/blocks/header/nav-config.tsx",
      type: "registry:component",
      target: "layouts/home/header/nav-config.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/header/header-02/layout.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["header"],
    meta: undefined,
  },
  }