/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "zone-select": {
    name: "zone-select",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","label","command","popover","https://laviecn.vercel.app/r/use-filter-zone.json"],
    files: [{
      path: "registry/components/zone-select.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/zone-select.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "zone-filter": {
    name: "zone-filter",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","input","scroll-area","https://laviecn.vercel.app/r/use-filter-zone.json"],
    files: [{
      path: "registry/components/zone-filter.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/zone-filter.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-to-top": {
    name: "scroll-to-top",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/components/scroll-to-top.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/scroll-to-top.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "json-table": {
    name: "json-table",
    description: "",
    type: "registry:component",
    registryDependencies: ["button","input","scroll-area","table","utils"],
    files: [{
      path: "registry/components/json-table.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/json-table.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "zone-select-demo": {
    name: "zone-select-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/zone-select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/zone-select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "zone-filter-demo": {
    name: "zone-filter-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/zone-filter-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/zone-filter-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-to-top-demo": {
    name: "scroll-to-top-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/scroll-to-top-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-to-top-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sotienthanhchu-demo": {
    name: "sotienthanhchu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/sotienthanhchu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/sotienthanhchu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "json-table-demo": {
    name: "json-table-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/examples/json-table-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/json-table-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "use-filter-fone": {
    name: "use-filter-fone",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-filter-zone.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/use-filter-zone.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sotienthanhchu": {
    name: "sotienthanhchu",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/utils/sotienthanhchu.ts",
      type: "registry:lib",
      target: "utils/sotienthanhchu.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/utils/sotienthanhchu.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }